version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
      docker: 18      
    commands:
      - echo Nothing to install, container image should have it all based on what we selected
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=535243943550.dkr.ecr.us-east-1.amazonaws.com/mmladminportal
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      
      - echo Just listing basic information about the environment
      - which mvn
      - mvn -version
      - pwd
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - echo Build completed on `date`
      - echo Working on creating the tar ball with the WAR and AppSpec file for CodeDeploy
      - mkdir appfiles
      - cd appfiles
      - cp ../target/managemylearning-admin-portal-0.0.1-SNAPSHOT.jar mmladminportal.jar
      - cp ../appspec.yml .
      - cp ../runAdminPortal.sh runAdminPortal.sh    
      - cp ../shutdown.sh shutdown.sh       
      - ls -al
      - tar -zcvf ../target/MMLAdminPortal.tar.gz *.*
      - cd ..
  post_build:
    commands:
      - echo Docker image creation started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"mmladminportal","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
# IMPORTANT
# You have to use the tar.gz if you are manually executing CodeDeploy
#    - target/MMLAdminPortal.tar.gz
# Use the individual files if you are using the CodeDeploy from CodePipeline
# Reason is pipeline does not untar and errors out saying that the appspec file is not there
    - appfiles/appspec.yml
    - appfiles/mmladminportal.jar
    - appfiles/runAdminPortal.sh
    - appfiles/shutdown.sh    
  discard-paths: yes
